version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_CONTAINER_PORT
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_CONTAINER_PORT
    env_file:
      - ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQL_CONTAINER_PORT/$MYSQL_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'